#!/bin/bash

ln -s /usr/local/lib/libgrpc++_unsecure.so.1.3.0 /usr/local/lib/libgrpc++_unsecure.so.3
ln -s /usr/local/lib/libgrpc++_unsecure.so.3 /usr/local/lib/libgrpc++_unsecure.so.1
ln -s /usr/local/lib/libgrpc++_unsecure.so.1.3.0 /usr/local/lib/libgrpc++_unsecure.so

ln -s /usr/local/lib/libgrpc-c.so.0.0.0 /usr/local/lib/libgrpc-c.so.0
ln -s /usr/local/lib/libgrpc-c.so.0.0.0 /usr/local/lib/libgrpc-c.so
ln -s /usr/local/lib/libgrpc_unsecure.so.3.0.0 /usr/local/lib/libgrpc_unsecure.so.3

ln -s /usr/local/lib/libgrpc++_cronet.so.1.3.0 /usr/local/lib/libgrpc++_cronet.so.1

ln -s /usr/local/lib/libprotobuf-c.so.1.0.0 /usr/local/lib/libprotobuf-c.so.1

ln -s /usr/local/lib/libgrpc++.so.1.3.0 /usr/local/lib/libgrpc++.so.3
ln -s /usr/local/lib/libgrpc++.so.3 /usr/local/lib/libgrpc++.so.1

ln -s /usr/local/lib/libvpp-agent-api.so.0.0.0 /usr/local/lib/libvpp-agent-api.so.0

ln -s /usr/local/lib/libgpr.so.3.0.0 /usr/local/lib/libgpr.so.3

ln -s /usr/local/lib/libgrpc++_reflection.so.1.3.0 /usr/local/lib/libgrpc++_reflection.so.3
ln -s /usr/local/lib/libgrpc++_reflection.so.3 /usr/local/lib/libgrpc++_reflection.so.1

ln -s /usr/local/lib/libgrpc++_error_details.so.1.3.0 /usr/local/lib/libgrpc++_error_details.so.3
ln -s /usr/local/lib/libgrpc++_error_details.so.3 /usr/local/lib/libgrpc++_error_details.so.1

ln -s /usr/local/lib/libgrpc.so.3.0.0 /usr/local/lib/libgrpc.so.3

