#!/bin/bash

ln -s /usr/local/lib/libgrpc++_unsecure.so.1.27.0 /usr/local/lib/libgrpc++_unsecure.so.1
ln -s /usr/local/lib/libgrpc++_unsecure.so.1.27.0 /usr/local/lib/libgrpc++_unsecure.so

ln -s /usr/local/lib/libgrpc_unsecure.so.9.0.0 /usr/local/lib/libgrpc_unsecure.so.9

ln -s /usr/local/lib/libgrpc_cronet.so.9.0.0 /usr/local/lib/libgrpc_cronet.so.9
ln -s /usr/local/lib/libgrpc_cronet.so.9.0.0 /usr/local/lib/libgrpc_cronet.so

ln -s /usr/local/lib/libgrpc++.so.1.27.0 /usr/local/lib/libgrpc++.so.1

ln -s /usr/local/lib/libgpr.so.9.0.0 /usr/local/lib/libgpr.so.9

ln -s /usr/local/lib/libgrpc++_reflection.so.1.27.0 /usr/local/lib/libgrpc++_reflection.so.1
ln -s /usr/local/lib/libgrpc++_reflection.so.1.27.0 /usr/local/lib/libgrpc++_reflection.so

ln -s /usr/local/lib/libgrpc++_error_details.so.1.27.0 /usr/local/lib/libgrpc++_error_details.so.1
ln -s /usr/local/lib/libgrpc++_error_details.so.1.27.0 /usr/local/lib/libgrpc++_error_details.so

ln -s /usr/local/lib/libgrpc.so.9.0.0 /usr/local/lib/libgrpc.so.9

ln -s /usr/local/lib/libprotobuf.so.10.0.0 /usr/local/lib/libprotobuf.so
